---
title: "Client Report - Project 0"
subtitle: "Course DS 250"
author: "Rebecca Roeth"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

_THIS `.qmd` FILE SHOULD BE USED TO WRITE YOUR REPORT.  YOU WILL NEED TO COMPILE THE REPORT INTO A `.html` DOCUMENT AND SUBMIT IT ON CANVAS._

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch
A brief assessment of a dataset from the US Environmental Protection Agency about 38 models of car which includes information about the highway miles per gallon, engine displacement, type of car, model, year, manufacturer, etc.

*Note:*
Using https://byuistats.github.io/DS250-Course/Projects/project_0.html for  assignment description 

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
url = "https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv"
mpg = pd.read_csv(url)
```
__Highlight the Questions and Tasks__

## Question|Task 2
__In VS Code, write a python script to create the example chart from section 3.
2.2 of the textbook (part of the assigned readings). Note that you will be 
using Plotly Express to display the chart instead of Altair which is used in 
the book.__ 

Bellow is the graph that can be found in the textbook.

```{python}
chart = px.scatter(mpg,  
    x="displ", 
    y="hwy",
    title = "Car's Engine size and Car's Fuel Efficiency",
    labels ={"displ": "Car Engine Size, litres", 
             "hwy": "Miles per Gallon (mpg)"},
)

chart.show()
```

*Some conclusions we can make"*
* The smaller the car engine, the better mpg ratio the car will have
* The larger the car engine, the car can have worse mpg ratio
* There are more cars with smaller car engines than there are cars with larger car engines
__Further Practice__
*Is there a relationship between the type of car and the relationship between its engine size and fuel efficiency?*

```{python}
chart = px.scatter(mpg,  
    x="displ", 
    y="hwy",
    title = "Car's Engine size and Fuel Efficiency by Type of Car",
    color = "class",
    labels ={"displ": "Car Engine Size, litres", 
             "hwy": "Miles per Gallon (mpg)", 
             "class": "Type"},
)

chart.show()
```

*Some conclusions we can make:*
* Compact and Subcompact cars tend to have smaller car engines
* Subcompact cars can have the best mpg ratio
* Pickups and SUVs have a range of car engine sizes but generally have a poor mpg retio 
* There are not many 2 seaters but they have some of the largest car engines

## Question|Task 3
__Your final report should also include the markdown table created from the following (assuming you have mpg from question 2).__

```{python}
print(mpg
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
  .to_markdown(index=False))

```

*Some conclusions we can make:*
Not many conclusions can be made from such a small sample size (5 entries). Additionally, these are the top five entries meaning we can't even assume this table is representing the whole even somewhat accurately like a randomized order tabled might.
